Repository dapr/components-contrib, pull requests merged in 2021-01, with the labels that each got.

#561 Adds BulkGetSecrets method to the SecretStore interface
  secretstores/Readme.md
Labels: documentation

#622 Add CosmosDB state store conformance tests
  .github/workflows/conformance.yml
  go.mod
  tests/config/state/cosmosdb/statestore.yaml
  tests/config/state/tests.yml
  tests/conformance/README.md
  tests/conformance/common.go
  tests/conformance/common_test.go
Labels: do-not-merge

#632 Fix get bulk secret for hashicorp vault.
  secretstores/hashicorp/vault/vault.go
Labels: kind/bug
