Repository dapr/components-contrib, pull requests merged in 2022-08, with the labels that each got.

#1925 pubsub.snssqs: Support regions in other AWS partitions
  pubsub/aws/snssqs/metadata.go
  pubsub/aws/snssqs/snssqs.go
  pubsub/aws/snssqs/snssqs_test.go
Labels: do-not-merge, documentation required

#1924 [pubsub/jetstream]: allow tls client authentication
  pubsub/jetstream/jetstream.go
  pubsub/jetstream/metadata.go
  pubsub/jetstream/metadata_test.go
Labels: automerge

#1934 Addresses Fossa Failures due to Apache Dubbo indirect dependency
  go.mod
  go.sum
Labels: automerge

#1936 Updated codecov Action to v3
  .codecov.yaml
  .github/workflows/components-contrib.yml
Labels: automerge

#1904 Ensure we're using the right version of cenkalti/backoff
  tests/certification/flow/retry/retry.go
  tests/certification/go.mod
  tests/certification/pubsub/mqtt/go.mod
  tests/certification/pubsub/mqtt/mqtt_test.go
Labels: automerge

#1908 Add auto-completion flag for Zeebe
  bindings/zeebe/jobworker/jobworker.go
  go.mod
  go.sum
  tests/e2e/bindings/zeebe/command/activate_jobs_test.go
  tests/e2e/bindings/zeebe/command/cancel_instance_test.go
  tests/e2e/bindings/zeebe/command/complete_job_test.go
  tests/e2e/bindings/zeebe/command/create_instance_test.go
  tests/e2e/bindings/zeebe/command/deploy_process_test.go
  tests/e2e/bindings/zeebe/command/fail_job_test.go
  tests/e2e/bindings/zeebe/command/publish_message_test.go
  tests/e2e/bindings/zeebe/command/set_variables_test.go
  tests/e2e/bindings/zeebe/command/throw_error_test.go
  tests/e2e/bindings/zeebe/command/topology_test.go
  tests/e2e/bindings/zeebe/command/update_job_retries_test.go
  tests/e2e/bindings/zeebe/docker-compose.yml
  tests/e2e/bindings/zeebe/helper.go
  tests/e2e/bindings/zeebe/jobworker/jobworker_test.go
  tests/e2e/bindings/zeebe/processes/calc.bpmn
Labels: automerge

#1930 Ensure rethinkdb complies with state.TransactionalStore
  state/rethinkdb/rethinkdb.go
  state/rethinkdb/rethinkdb_test.go
Labels: automerge

#1920 Azure App Configuration: Implemented get all keys
  configuration/azure/appconfig/appconfig.go
Labels: automerge

#1846 Certification tests for env/file secrets stores #1761
  .github/workflows/certification.yml
  tests/certification/secretstores/local/env/components/localsecrets.yaml
  tests/certification/secretstores/local/env/config.yaml
  tests/certification/secretstores/local/env/envstore_test.go
  tests/certification/secretstores/local/env/go.mod
  tests/certification/secretstores/local/env/go.sum
  tests/certification/secretstores/local/file/components/customnestedseparator/localsecrets.yaml
  tests/certification/secretstores/local/file/components/defaultnestedseparator/localsecrets.yaml
  tests/certification/secretstores/local/file/components/secrets.json
  tests/certification/secretstores/local/file/config.yaml
  tests/certification/secretstores/local/file/filestore_test.go
  tests/certification/secretstores/local/file/go.mod
  tests/certification/secretstores/local/file/go.sum
Labels: automerge

#1873 add a new binding component : alicloud sls log storage
  bindings/alicloud/sls/sls.go
  bindings/alicloud/sls/sls_test.go
  go.mod
  go.sum
Labels: automerge

#1946 Enable CosmosDB Binding conformance test
  .github/workflows/conformance.yml
Labels: automerge

#1949 Conformance test for Memcached Statestore (makes this component Beta)
  .github/infrastructure/docker-compose-memcached.yml
  .github/workflows/conformance.yml
  state/memcached/memcached.go
  tests/config/state/memcached/statestore.yaml
  tests/config/state/tests.yml
  tests/conformance/common.go
Labels: automerge

#1954 Removing the use of the ioutil package And Fix CVE-2021-42576
  bindings/alicloud/dingtalk/webhook/webhook_test.go
  bindings/apns/apns_test.go
  bindings/azure/eventgrid/eventgrid.go
  bindings/azure/signalr/signalr.go
  bindings/azure/signalr/signalr_test.go
  bindings/gcp/bucket/bucket.go
  bindings/http/http.go
  bindings/http/http_test.go
  bindings/huawei/obs/obs.go
  bindings/huawei/obs/obs_test.go
  bindings/localstorage/localstorage.go
  bindings/mysql/mysql.go
  bindings/twilio/sms/sms_test.go
  go.mod
  go.sum
  internal/authentication/azure/auth.go
  internal/authentication/azure/auth_test.go
  middleware/http/nethttpadaptor/nethttpadaptor.go
  middleware/http/nethttpadaptor/nethttpadaptor_test.go
  secretstores/hashicorp/vault/vault.go
  secretstores/hashicorp/vault/vault_test.go
  secretstores/local/file/filestore.go
  state/azure/cosmosdb/cosmosdb_query_test.go
  state/cockroachdb/cockroachdb_query_test.go
  state/mongodb/mongodb_query_test.go
  state/mysql/mySQLFactory.go
  state/mysql/mysql_integration_test.go
  state/oci/objectstorage/objectstorage.go
  state/postgresql/postgresql_query_test.go
  state/query/query_test.go
  state/redis/redis_query_test.go
  state/rethinkdb/rethinkdb.go
  tests/certification/bindings/azure/blobstorage/blobstorage_test.go
  tests/conformance/common.go
  tests/conformance/standalone_loader.go
  tests/conformance/utils/utils.go
  tests/e2e/bindings/zeebe/helper.go
Labels: automerge

#1959 Backport #1957 into release-1.8
  internal/component/azure/servicebus/subscription.go
Labels: automerge

#1961 fix: bindings.ipfs unit test
  bindings/ipfs/ipfs_test.go
Labels: autoupdate

#1951 optimize: add e2etests buildtags for e2e
  tests/e2e/pubsub/jetstream/authentication/authentication_test.go
Labels: automerge

#1958 Update code to reflect renaming on UnlockResponse.Status
  lock/redis/standalone.go
  lock/responses.go
Labels: automerge

#1965 fix(kafka): ConsumeClaim should not return err when retry recovery failed
  internal/component/kafka/consumer.go
Labels: automerge

#1911 Allow metadata to flow through service bus queue
  bindings/azure/servicebusqueues/servicebusqueues.go
  tests/certification/bindings/azure/servicebusqueues/README.md
  tests/certification/bindings/azure/servicebusqueues/servicebusqueue_test.go
Labels: automerge

#1995 Upgrade cert tests to go1.19, latest dapr
  tests/certification/bindings/alicloud/dubbo/go.mod
  tests/certification/bindings/alicloud/dubbo/go.sum
  tests/certification/bindings/alicloud/nacos/go.mod
  tests/certification/bindings/alicloud/nacos/go.sum
  tests/certification/bindings/azure/blobstorage/go.mod
  tests/certification/bindings/azure/blobstorage/go.sum
  tests/certification/bindings/azure/cosmosdb/go.mod
  tests/certification/bindings/azure/cosmosdb/go.sum
  tests/certification/bindings/azure/eventhubs/go.mod
  tests/certification/bindings/azure/eventhubs/go.sum
  tests/certification/bindings/azure/servicebusqueues/go.mod
  tests/certification/bindings/azure/servicebusqueues/go.sum
  tests/certification/bindings/azure/storagequeues/go.mod
  tests/certification/bindings/azure/storagequeues/go.sum
  tests/certification/bindings/kafka/go.mod
  tests/certification/bindings/kafka/go.sum
  tests/certification/go.mod
  tests/certification/go.sum
  tests/certification/pubsub/azure/eventhubs/go.mod
  tests/certification/pubsub/azure/eventhubs/go.sum
  tests/certification/pubsub/kafka/go.mod
  tests/certification/pubsub/kafka/go.sum
  tests/certification/pubsub/mqtt/go.mod
  tests/certification/pubsub/mqtt/go.sum
  tests/certification/pubsub/rabbitmq/go.mod
  tests/certification/pubsub/rabbitmq/go.sum
  tests/certification/secretstores/azure/keyvault/go.mod
  tests/certification/secretstores/azure/keyvault/go.sum
  tests/certification/secretstores/local/env/go.mod
  tests/certification/secretstores/local/env/go.sum
  tests/certification/secretstores/local/file/go.mod
  tests/certification/secretstores/local/file/go.sum
  tests/certification/state/azure/blobstorage/go.mod
  tests/certification/state/azure/blobstorage/go.sum
  tests/certification/state/azure/tablestorage/go.mod
  tests/certification/state/azure/tablestorage/go.sum
  tests/certification/state/postgresql/go.mod
  tests/certification/state/postgresql/go.sum
  tests/certification/state/redis/go.mod
  tests/certification/state/redis/go.sum
  tests/certification/state/sqlserver/go.mod
  tests/certification/state/sqlserver/go.sum
Labels: automerge

#1996 make certification tests fail on build failure
  .github/workflows/certification.yml
Labels: automerge

#1937 Added certification tests for azure service bus pubsub
  .github/infrastructure/conformance/azure/setup-azure-conf-test.sh
  .github/workflows/certification.yml
  tests/certification/pubsub/azure/servicebus/README.md
  tests/certification/pubsub/azure/servicebus/components/authentication/localsecrets.yaml
  tests/certification/pubsub/azure/servicebus/components/authentication/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/components/consumer_one/localsecrets.yaml
  tests/certification/pubsub/azure/servicebus/components/consumer_one/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/components/consumer_two/localsecrets.yaml
  tests/certification/pubsub/azure/servicebus/components/consumer_two/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/components/default_ttl/localsecrets.yaml
  tests/certification/pubsub/azure/servicebus/components/default_ttl/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/components/entity_mgnt/localsecrets.yaml
  tests/certification/pubsub/azure/servicebus/components/entity_mgnt/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/config.yaml
  tests/certification/pubsub/azure/servicebus/go.mod
  tests/certification/pubsub/azure/servicebus/go.sum
  tests/certification/pubsub/azure/servicebus/servicebus_test.go
Labels: automerge

#1919 Added certification tests to rabbitMQ bindings
  .github/workflows/certification.yml
  tests/certification/bindings/rabbitmq/README.md
  tests/certification/bindings/rabbitmq/components/options/rabbitmq.yaml
  tests/certification/bindings/rabbitmq/components/retry/rabbitmq.yaml
  tests/certification/bindings/rabbitmq/components/standard/rabbitmq.yaml
  tests/certification/bindings/rabbitmq/components/ttl/rabbitmq_msg_ttl.yaml
  tests/certification/bindings/rabbitmq/components/ttl/rabbitmq_overwrite_ttl.yaml
  tests/certification/bindings/rabbitmq/components/ttl/rabbitmq_queue_ttl.yaml
  tests/certification/bindings/rabbitmq/config.yaml
  tests/certification/bindings/rabbitmq/docker-compose.yml
  tests/certification/bindings/rabbitmq/go.mod
  tests/certification/bindings/rabbitmq/go.sum
  tests/certification/bindings/rabbitmq/rabbitmq_test.go
Labels: automerge

#2002 Corrected module name in go mod file
  tests/certification/pubsub/azure/servicebus/go.mod
Labels: automerge

#2011 Fix makefile
  Makefile
Labels: automerge

#1771 fix: Converting configuration API response from an array to dictionary
  configuration/azure/appconfig/appconfig.go
  configuration/redis/redis.go
  configuration/redis/redis_test.go
  configuration/requests.go
  configuration/responses.go
  tests/certification/bindings/alicloud/dubbo/go.mod
  tests/certification/bindings/alicloud/dubbo/go.sum
  tests/certification/bindings/alicloud/nacos/go.mod
  tests/certification/bindings/alicloud/nacos/go.sum
  tests/certification/bindings/azure/blobstorage/go.mod
  tests/certification/bindings/azure/blobstorage/go.sum
  tests/certification/bindings/azure/cosmosdb/go.mod
  tests/certification/bindings/azure/cosmosdb/go.sum
  tests/certification/bindings/azure/eventhubs/go.mod
  tests/certification/bindings/azure/eventhubs/go.sum
  tests/certification/bindings/azure/servicebusqueues/go.mod
  tests/certification/bindings/azure/servicebusqueues/go.sum
  tests/certification/bindings/azure/storagequeues/go.mod
  tests/certification/bindings/azure/storagequeues/go.sum
  tests/certification/bindings/kafka/go.mod
  tests/certification/bindings/kafka/go.sum
  tests/certification/bindings/rabbitmq/go.mod
  tests/certification/bindings/rabbitmq/go.sum
  tests/certification/embedded/embedded.go
  tests/certification/go.mod
  tests/certification/go.sum
  tests/certification/pubsub/azure/eventhubs/go.mod
  tests/certification/pubsub/azure/eventhubs/go.sum
  tests/certification/pubsub/azure/servicebus/go.mod
  tests/certification/pubsub/azure/servicebus/go.sum
  tests/certification/pubsub/kafka/go.mod
  tests/certification/pubsub/kafka/go.sum
  tests/certification/pubsub/mqtt/go.mod
  tests/certification/pubsub/mqtt/go.sum
  tests/certification/pubsub/rabbitmq/go.mod
  tests/certification/pubsub/rabbitmq/go.sum
  tests/certification/secretstores/azure/keyvault/go.mod
  tests/certification/secretstores/azure/keyvault/go.sum
  tests/certification/secretstores/local/env/go.mod
  tests/certification/secretstores/local/env/go.sum
  tests/certification/secretstores/local/file/go.mod
  tests/certification/secretstores/local/file/go.sum
  tests/certification/state/azure/blobstorage/go.mod
  tests/certification/state/azure/blobstorage/go.sum
  tests/certification/state/azure/tablestorage/go.mod
  tests/certification/state/azure/tablestorage/go.sum
  tests/certification/state/postgresql/go.mod
  tests/certification/state/postgresql/go.sum
  tests/certification/state/redis/go.mod
  tests/certification/state/redis/go.sum
  tests/certification/state/sqlserver/go.mod
  tests/certification/state/sqlserver/go.sum
Labels: pinned

#2010 Fix typos in Apache Cassandra logs
  state/cassandra/cassandra.go
Labels: automerge

#2015 Enable conformance tests for rethinkdb
  .github/infrastructure/docker-compose-rethinkdb.yml
  .github/workflows/conformance.yml
  state/rethinkdb/rethinkdb.go
  tests/config/state/rethinkdb/statestore.yml
  tests/config/state/tests.yml
  tests/conformance/common.go
Labels: autoupdate

#2019 pin latest dapr/dapr in certification tests
  tests/certification/bindings/alicloud/dubbo/go.mod
  tests/certification/bindings/alicloud/dubbo/go.sum
  tests/certification/bindings/alicloud/nacos/go.mod
  tests/certification/bindings/alicloud/nacos/go.sum
  tests/certification/bindings/azure/blobstorage/go.mod
  tests/certification/bindings/azure/blobstorage/go.sum
  tests/certification/bindings/azure/cosmosdb/go.mod
  tests/certification/bindings/azure/cosmosdb/go.sum
  tests/certification/bindings/azure/eventhubs/go.mod
  tests/certification/bindings/azure/eventhubs/go.sum
  tests/certification/bindings/azure/servicebusqueues/go.mod
  tests/certification/bindings/azure/servicebusqueues/go.sum
  tests/certification/bindings/azure/storagequeues/go.mod
  tests/certification/bindings/azure/storagequeues/go.sum
  tests/certification/bindings/kafka/go.mod
  tests/certification/bindings/kafka/go.sum
  tests/certification/bindings/rabbitmq/go.mod
  tests/certification/bindings/rabbitmq/go.sum
  tests/certification/go.mod
  tests/certification/go.sum
  tests/certification/pubsub/azure/eventhubs/go.mod
  tests/certification/pubsub/azure/eventhubs/go.sum
  tests/certification/pubsub/azure/servicebus/go.mod
  tests/certification/pubsub/azure/servicebus/go.sum
  tests/certification/pubsub/kafka/go.mod
  tests/certification/pubsub/kafka/go.sum
  tests/certification/pubsub/mqtt/go.mod
  tests/certification/pubsub/mqtt/go.sum
  tests/certification/pubsub/rabbitmq/go.mod
  tests/certification/pubsub/rabbitmq/go.sum
  tests/certification/secretstores/azure/keyvault/go.mod
  tests/certification/secretstores/azure/keyvault/go.sum
  tests/certification/secretstores/local/env/go.mod
  tests/certification/secretstores/local/env/go.sum
  tests/certification/secretstores/local/file/go.mod
  tests/certification/secretstores/local/file/go.sum
  tests/certification/state/azure/blobstorage/go.mod
  tests/certification/state/azure/blobstorage/go.sum
  tests/certification/state/azure/tablestorage/go.mod
  tests/certification/state/azure/tablestorage/go.sum
  tests/certification/state/postgresql/go.mod
  tests/certification/state/postgresql/go.sum
  tests/certification/state/redis/go.mod
  tests/certification/state/redis/go.sum
  tests/certification/state/sqlserver/go.mod
  tests/certification/state/sqlserver/go.sum
Labels: automerge

#2022 Azure Service Bus Queues Binding: disable entity management option
  bindings/azure/servicebusqueues/metadata.go
  bindings/azure/servicebusqueues/servicebusqueues.go
  tests/certification/bindings/azure/servicebusqueues/components/disable_entity_mgmt/azure_service_bus_retry.yaml
  tests/certification/bindings/azure/servicebusqueues/servicebusqueue_test.go
  tests/certification/pubsub/azure/servicebus/components/entity_mgmt/localsecrets.yaml
  tests/certification/pubsub/azure/servicebus/components/entity_mgmt/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/servicebus_test.go
Labels: documentation required

#1979 AWS DynamoDB etag support
  state/aws/dynamodb/dynamodb.go
  state/aws/dynamodb/dynamodb_test.go
Labels: autoupdate

#2030 Reduce conformance test run frequency
  .github/workflows/conformance.yml
Labels: automerge

#2031 Conformance tests for Hashicorp Vault.
  .github/infrastructure/conformance/hashicorp/setup-hashicorp-vault-secrets.sh
  .github/infrastructure/docker-compose-hashicorp-vault.yml
  .github/workflows/conformance.yml
  tests/config/secretstores/hashicorp/vault/hashicorp-vault.yml
  tests/config/secretstores/tests.yml
  tests/conformance/common.go
Labels: automerge

#2025 Calculates and sends discord notification for Cert test coverage more than 80%
  .github/workflows/certification.yml
Labels: automerge

#2034 Added postgres conformance test for binding
  .github/workflows/conformance.yml
  tests/config/bindings/postgres/bindings.yml
  tests/config/bindings/tests.yml
  tests/conformance/common.go
Labels: automerge
