Repository dapr/components-contrib, pull requests merged in 2022-11, with the labels that each got.

#2241 Added cert test for state.mysql + Fixes including transactions
  .github/workflows/certification.yml
  .golangci.yml
  state/mysql/mysql.go
  state/mysql/mysql_certtests.go
  state/mysql/mysql_integration_test.go
  state/mysql/mysql_test.go
  tests/certification/flow/network/network.go
  tests/certification/state/mysql/README.md
  tests/certification/state/mysql/components/docker/default/mariadb.yaml
  tests/certification/state/mysql/components/docker/default/mysql.yaml
  tests/certification/state/mysql/config.yaml
  tests/certification/state/mysql/docker-compose.yaml
  tests/certification/state/mysql/go.mod
  tests/certification/state/mysql/go.sum
  tests/certification/state/mysql/mysql_test.go
  tests/certification/state/postgresql/README.md
  tests/certification/state/postgresql/postgresql_test.go
Labels: documentation required, autoupdate

#2234 PubSub: Fall back to 'consumerID' when group not present
  pubsub/aws/snssqs/metadata.go
  pubsub/jetstream/metadata.go
  pubsub/metadata.go
  pubsub/rocketmq/metadata.go
Labels: automerge

#2245 Updated depguard linter config
  .golangci.yml
  bindings/mysql/mysql.go
  go.mod
  go.sum
  state/aerospike/aerospike.go
  state/alicloud/tablestore/tablestore.go
  state/alicloud/tablestore/tablestore_test.go
  state/azure/blobstorage/blobstorage.go
  state/cockroachdb/cockroachdb_access.go
  state/cockroachdb/cockroachdb_query.go
  state/cockroachdb/cockroachdb_query_test.go
  state/couchbase/couchbase.go
  state/hashicorp/consul/consul.go
  state/in-memory/in_memory_test.go
  state/mongodb/mongodb.go
  state/postgresql/postgresdbaccess.go
  state/postgresql/postgresql_query.go
  state/redis/redis.go
  state/redis/redis_test.go
  state/rethinkdb/rethinkdb.go
  state/sqlserver/sqlserver.go
  state/zookeeper/zk.go
  state/zookeeper/zk_test.go
  tests/certification/state/azure/blobstorage/go.mod
  tests/certification/state/azure/blobstorage/go.sum
  tests/certification/state/mongodb/go.mod
  tests/certification/state/mongodb/go.sum
  tests/certification/state/postgresql/go.mod
  tests/certification/state/postgresql/go.sum
  tests/certification/state/redis/go.mod
  tests/certification/state/redis/go.sum
  tests/certification/state/sqlserver/go.mod
  tests/certification/state/sqlserver/go.sum
Labels: automerge

#2262 fix kubernetes nameresolution customize configuration
  nameresolution/kubernetes/kubernetes.go
  nameresolution/kubernetes/kubernetes_test.go
Labels: automerge

#2202 pubsub jetstream: set Nats-Msg-Id for message deduplication #2200
  pubsub/jetstream/jetstream.go
Labels: automerge

#2198 Add rocketmq configuration items. Add orderly message.
  go.mod
  go.sum
  pubsub/rocketmq/metadata.go
  pubsub/rocketmq/metadata_test.go
  pubsub/rocketmq/rocketmq.go
  pubsub/rocketmq/rocketmq_test.go
Labels: automerge, documentation required

#2263 Storage Queues Binding: Add b64encoding option for messages
  bindings/azure/storagequeues/storagequeues.go
  tests/certification/bindings/azure/storagequeues/components/decode/azure_queue_storage.yaml
  tests/certification/bindings/azure/storagequeues/storagequeue_test.go
Labels: automerge, documentation required

#2244 Add `streamName` and epxlicitly bind to consumer and stream
  go.mod
  go.sum
  pubsub/jetstream/jetstream.go
  pubsub/jetstream/metadata.go
  tests/e2e/pubsub/jetstream/go.mod
  tests/e2e/pubsub/jetstream/go.sum
Labels: automerge, documentation required

#2093 Add pubsub rabbitmq TTL support
  pubsub/rabbitmq/metadata.go
  pubsub/rabbitmq/rabbitmq.go
  tests/certification/pubsub/rabbitmq/README.md
  tests/certification/pubsub/rabbitmq/components/ttl/rabbitmq_msg_ttl.yaml
  tests/certification/pubsub/rabbitmq/components/ttl/rabbitmq_overwrite_ttl.yaml
  tests/certification/pubsub/rabbitmq/components/ttl/rabbitmq_queue_ttl.yaml
  tests/certification/pubsub/rabbitmq/rabbitmq_test.go
Labels: automerge, documentation required

#2275 Upgrade linter and fix linter issues
  .github/workflows/components-contrib.yml
  .golangci.yml
  bindings/alicloud/dingtalk/webhook/webhook_test.go
  bindings/gcp/bucket/bucket.go
  bindings/rethinkdb/statechange/statechange.go
  pubsub/jetstream/metadata_test.go
  pubsub/rabbitmq/rabbitmq.go
  secretstores/azure/keyvault/keyvault.go
  secretstores/hashicorp/vault/vault.go
  state/oci/objectstorage/objectstorage.go
  state/sqlserver/migration.go
  tests/conformance/utils/utils.go
Labels: automerge

#2272 Adding KubeMQ Binding - Queue
  .github/workflows/conformance.yml
  .golangci.yml
  bindings/kubemq/kubemq.go
  bindings/kubemq/kubemq_integration_test.go
  bindings/kubemq/kubemq_test.go
  bindings/kubemq/options.go
  tests/config/bindings/kubemq/binding.yml
  tests/config/bindings/tests.yml
  tests/conformance/common.go
Labels: documentation required

#2285 Adding CosmosDB and TableStorage Dapr User Agents
  bindings/azure/cosmosdb/cosmosdb.go
  state/azure/cosmosdb/cosmosdb.go
  state/azure/tablestorage/tablestorage.go
Labels: automerge

#2278 ASQ Binding: Make visibilityTimeout configurable
  bindings/azure/storagequeues/storagequeues.go
  bindings/azure/storagequeues/storagequeues_test.go
Labels: automerge, documentation required

#2295 jetstream pubsub now supports token based auth
  pubsub/jetstream/jetstream.go
  pubsub/jetstream/metadata.go
  pubsub/jetstream/metadata_test.go
Labels: automerge

#2303 Fix state.in-memory and enable conformance tests
  .github/workflows/conformance.yml
  state/in-memory/in_memory.go
  state/in-memory/in_memory_test.go
  tests/config/state/in-memory/statestore.yaml
  tests/config/state/tests.yml
  tests/conformance/common.go
Labels: automerge

#2304 Add conformance test for TTL in state stores
  tests/config/state/tests.yml
  tests/conformance/state/state.go
Labels: automerge

#2290 Azure Blobstorage Binding and State Store: Migrate to Track2 Azure SDK
  bindings/azure/blobstorage/blobstorage.go
  bindings/azure/blobstorage/blobstorage_test.go
  go.mod
  go.sum
  internal/component/azure/blobstorage/client.go
  internal/component/azure/blobstorage/client_test.go
  internal/component/azure/blobstorage/metadata.go
  internal/component/azure/blobstorage/metadata_test.go
  internal/component/azure/blobstorage/request.go
  internal/component/azure/blobstorage/request_test.go
  state/azure/blobstorage/blobstorage.go
  state/azure/blobstorage/blobstorage_test.go
  tests/certification/bindings/azure/blobstorage/blobstorage_test.go
  tests/certification/bindings/azure/blobstorage/go.mod
  tests/certification/bindings/azure/blobstorage/go.sum
  tests/certification/bindings/azure/cosmosdb/go.mod
  tests/certification/bindings/azure/cosmosdb/go.sum
  tests/certification/bindings/azure/eventhubs/go.mod
  tests/certification/bindings/azure/eventhubs/go.sum
  tests/certification/bindings/azure/servicebusqueues/go.mod
  tests/certification/bindings/azure/servicebusqueues/go.sum
  tests/certification/bindings/azure/storagequeues/go.mod
  tests/certification/bindings/azure/storagequeues/go.sum
  tests/certification/pubsub/azure/eventhubs/go.mod
  tests/certification/pubsub/azure/eventhubs/go.sum
  tests/certification/pubsub/azure/servicebus/topics/go.mod
  tests/certification/pubsub/azure/servicebus/topics/go.sum
  tests/certification/secretstores/azure/keyvault/go.mod
  tests/certification/secretstores/azure/keyvault/go.sum
  tests/certification/state/azure/blobstorage/go.mod
  tests/certification/state/azure/blobstorage/go.sum
  tests/certification/state/azure/cosmosdb/go.mod
  tests/certification/state/azure/cosmosdb/go.sum
  tests/certification/state/azure/tablestorage/go.mod
  tests/certification/state/azure/tablestorage/go.sum
Labels: automerge

#2299 Add mqtt retained information to pubsub message metadata
  pubsub/mqtt/mqtt.go
Labels: automerge, documentation required

#2312 Add missing filter subject in Jetstream pubsub
  pubsub/jetstream/jetstream.go
Labels: automerge

#2321 Allow non-200 responses to be treated as non-errors
  bindings/http/http.go
  bindings/http/http_test.go
Labels: automerge, documentation required
