Repository dapr/components-contrib, pull requests merged in 2022-09, with the labels that each got.

#2043 Add prefix option to AWS SSM Parameter Store secret store component
  secretstores/aws/parameterstore/parameterstore.go
  secretstores/aws/parameterstore/parameterstore_test.go
Labels: automerge

#2040 Add certification tests for MongoDB state store
  .github/workflows/certification.yml
  tests/certification/state/mongodb/README.md
  tests/certification/state/mongodb/components/docker/default/mongodbstatestore.yaml
  tests/certification/state/mongodb/components/docker/singleNode/mongodbstatestore.yaml
  tests/certification/state/mongodb/components/docker/validReadWriteConcernAndTimeout/mongodbstatestore.yaml
  tests/certification/state/mongodb/config.yaml
  tests/certification/state/mongodb/docker-compose-cluster.yml
  tests/certification/state/mongodb/docker-compose-single.yml
  tests/certification/state/mongodb/go.mod
  tests/certification/state/mongodb/go.sum
  tests/certification/state/mongodb/mongo_setup.sh
  tests/certification/state/mongodb/mongodb_test.go
Labels: automerge

#1972 Certification test for Azure CosmosDB Statestore
  .github/workflows/certification.yml
  tests/certification/state/azure/cosmosdb/README.md
  tests/certification/state/azure/cosmosdb/components/aadtest/cosmosdb.yaml
  tests/certification/state/azure/cosmosdb/components/aadtest/localsecrets.yaml
  tests/certification/state/azure/cosmosdb/components/basictest/cosmosdb.yaml
  tests/certification/state/azure/cosmosdb/components/basictest/localsecrets.yaml
  tests/certification/state/azure/cosmosdb/config.yaml
  tests/certification/state/azure/cosmosdb/cosmosdb_test.go
  tests/certification/state/azure/cosmosdb/go.mod
  tests/certification/state/azure/cosmosdb/go.sum
Labels: automerge

#2069 SecretStores advertise supported Features().
  secretstores/alicloud/parameterstore/parameterstore.go
  secretstores/alicloud/parameterstore/parameterstore_test.go
  secretstores/aws/parameterstore/parameterstore.go
  secretstores/aws/parameterstore/parameterstore_test.go
  secretstores/aws/secretmanager/secretmanager.go
  secretstores/aws/secretmanager/secretmanager_test.go
  secretstores/azure/keyvault/keyvault.go
  secretstores/azure/keyvault/keyvault_test.go
  secretstores/feature.go
  secretstores/gcp/secretmanager/secretmanager.go
  secretstores/gcp/secretmanager/secretmanager_test.go
  secretstores/hashicorp/vault/vault.go
  secretstores/hashicorp/vault/vault_test.go
  secretstores/huaweicloud/csms/csms.go
  secretstores/huaweicloud/csms/csms_test.go
  secretstores/kubernetes/kubernetes.go
  secretstores/kubernetes/kubernetes_test.go
  secretstores/local/env/envstore.go
  secretstores/local/env/envstore_test.go
  secretstores/local/file/filestore.go
  secretstores/local/file/filestore_test.go
  secretstores/secret_store.go
Labels: automerge, documentation required

#2066 Update log level for successful retry
  pubsub/azure/eventhubs/eventhubs.go
Labels: automerge

#1807 refactored aws sqs policy inserting
  pubsub/aws/snssqs/policy.go
  pubsub/aws/snssqs/snssqs.go
  pubsub/aws/snssqs/snssqs_test.go
Labels: automerge

#1833 middleware: changes wasm basic to use waPC
  README.md
  bindings/README.md
  configuration/README.md
  go.mod
  go.sum
  middleware/README.md
  middleware/http/wasm/README.md
  middleware/http/wasm/basic/Makefile
  middleware/http/wasm/basic/README.md
  middleware/http/wasm/basic/basic.go
  middleware/http/wasm/basic/basic_test.go
  middleware/http/wasm/basic/example/Makefile
  middleware/http/wasm/basic/example/example.go
  middleware/http/wasm/basic/example/example.wasm
  middleware/http/wasm/basic/example/go.mod
  middleware/http/wasm/basic/example/go.sum
  middleware/http/wasm/basic/hello.wasm
  middleware/http/wasm/basic/internal/e2e-guests/Makefile
  middleware/http/wasm/basic/internal/e2e-guests/README.md
  middleware/http/wasm/basic/internal/e2e-guests/go.mod
  middleware/http/wasm/basic/internal/e2e-guests/go.sum
  middleware/http/wasm/basic/internal/e2e-guests/output/main.go
  middleware/http/wasm/basic/internal/e2e-guests/output/main.wasm
  middleware/http/wasm/basic/internal/e2e_test.go
  middleware/http/wasm/basic/internal/test/logger.go
  nameresolution/README.md
  nameresolution/consul/README.md
  pubsub/README.md
  secretstores/README.md
  state/README.md
  tests/certification/bindings/alicloud/dubbo/go.mod
  tests/certification/bindings/alicloud/dubbo/go.sum
Labels: automerge, documentation required

#1817 RocketMQ fix metadata properties
  pubsub/rocketmq/metadata.go
  pubsub/rocketmq/metadata_test.go
  pubsub/rocketmq/rocketmq.go
  pubsub/rocketmq/rocketmq_test.go
Labels: automerge

#2057 Added certification tests for postgres output binding
  .github/workflows/certification.yml
  tests/certification/bindings/postgres/README.md
  tests/certification/bindings/postgres/components/standard/postgres.yaml
  tests/certification/bindings/postgres/config.yaml
  tests/certification/bindings/postgres/docker-compose.yml
  tests/certification/bindings/postgres/go.mod
  tests/certification/bindings/postgres/go.sum
  tests/certification/bindings/postgres/postgres_test.go
Labels: automerge, documentation required

#2078 Updated docs for creating new components
  docs/developing-component.md
Labels: automerge

#2064 Implements getLabelFromMetadata Fixing #2062
  configuration/azure/appconfig/appconfig.go
Labels: automerge, documentation required

#2017 read record header as metadata if available in kafka
  internal/component/kafka/consumer.go
Labels: automerge

#2111 actually disable cert test coverage notifications on PR and ok-to-test
  .github/workflows/certification.yml
Labels: automerge

#2097 Fix getAll configuration Api for azure app config
  configuration/azure/appconfig/appconfig.go
  configuration/azure/appconfig/appconfig_test.go
  go.mod
  go.sum
Labels: automerge

#2039 optimize(middleware): Middleware to middleware.Middleware API
  middleware/http/bearer/bearer_middleware.go
  middleware/http/oauth2/oauth2_middleware.go
  middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware.go
  middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware_test.go
  middleware/http/opa/middleware.go
  middleware/http/ratelimit/ratelimit_middleware.go
  middleware/http/routerchecker/routerchecker_middleware.go
  middleware/http/sentinel/middleware.go
  middleware/http/sentinel/middleware_test.go
Labels: automerge

#2125 Fix kafka session done merge master
  internal/component/kafka/consumer.go
  middleware/http/bearer/bearer_middleware.go
  middleware/http/oauth2/oauth2_middleware.go
  middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware.go
  middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware_test.go
  middleware/http/opa/middleware.go
  middleware/http/ratelimit/ratelimit_middleware.go
  middleware/http/routerchecker/routerchecker_middleware.go
  middleware/http/sentinel/middleware.go
  middleware/http/sentinel/middleware_test.go
Labels: automerge

#2063 Support for Postgresql as configuration store
  configuration/postgres/metadata.go
  configuration/postgres/postgres.go
  configuration/postgres/postgres_test.go
  go.mod
  go.sum
  tests/certification/bindings/alicloud/dubbo/go.mod
  tests/certification/bindings/alicloud/dubbo/go.sum
  tests/certification/bindings/azure/blobstorage/go.mod
  tests/certification/bindings/azure/blobstorage/go.sum
  tests/certification/bindings/azure/cosmosdb/go.mod
  tests/certification/bindings/azure/cosmosdb/go.sum
  tests/certification/bindings/azure/eventhubs/go.mod
  tests/certification/bindings/azure/eventhubs/go.sum
  tests/certification/bindings/azure/servicebusqueues/go.mod
  tests/certification/bindings/azure/servicebusqueues/go.sum
  tests/certification/bindings/azure/storagequeues/go.mod
  tests/certification/bindings/azure/storagequeues/go.sum
  tests/certification/bindings/kafka/go.mod
  tests/certification/bindings/kafka/go.sum
  tests/certification/bindings/postgres/go.mod
  tests/certification/bindings/postgres/go.sum
  tests/certification/pubsub/azure/eventhubs/go.mod
  tests/certification/pubsub/azure/eventhubs/go.sum
  tests/certification/pubsub/azure/servicebus/go.mod
  tests/certification/pubsub/azure/servicebus/go.sum
  tests/certification/pubsub/kafka/go.mod
  tests/certification/pubsub/kafka/go.sum
  tests/certification/secretstores/azure/keyvault/go.mod
  tests/certification/secretstores/azure/keyvault/go.sum
  tests/certification/state/azure/blobstorage/go.mod
  tests/certification/state/azure/blobstorage/go.sum
  tests/certification/state/azure/cosmosdb/go.mod
  tests/certification/state/azure/cosmosdb/go.sum
  tests/certification/state/azure/tablestorage/go.mod
  tests/certification/state/azure/tablestorage/go.sum
  tests/certification/state/mongodb/go.mod
  tests/certification/state/mongodb/go.sum
  tests/certification/state/postgresql/go.mod
  tests/certification/state/postgresql/go.sum
  tests/certification/state/sqlserver/go.mod
  tests/certification/state/sqlserver/go.sum
  tests/e2e/pubsub/jetstream/go.mod
  tests/e2e/pubsub/jetstream/go.sum
Labels: automerge

#2116 Certification tests for MemCached State Store component.
  .github/workflows/certification.yml
  state/memcached/memcached.go
  state/memcached/memcached_test.go
  tests/certification/state/memcached/README.md
  tests/certification/state/memcached/components/docker/20secondsTimeout/memcachedstatestore.yaml
  tests/certification/state/memcached/components/docker/default/memcachedstatestore.yaml
  tests/certification/state/memcached/config.yaml
  tests/certification/state/memcached/docker-compose.yml
  tests/certification/state/memcached/go.mod
  tests/certification/state/memcached/go.sum
  tests/certification/state/memcached/memcached_test.go
Labels: automerge, documentation required

#2104 Update mqtt.go
  pubsub/mqtt/metadata.go
  pubsub/mqtt/mqtt.go
Labels: automerge

#2124 Remove recover from Redis config store
  configuration/redis/redis.go
Labels: automerge

#2129 Added username and password arguments to pubsub.rabbitmq metadata
  pubsub/rabbitmq/metadata.go
  pubsub/rabbitmq/metadata_test.go
  pubsub/rabbitmq/rabbitmq.go
  pubsub/rabbitmq/rabbitmq_test.go
Labels: automerge, documentation required

#2123 Add time to CloudEvent automatically if not present
  pubsub/envelope.go
  pubsub/envelope_test.go
Labels: do-not-merge

#2077 Component metadata schema and tools
  .build-tools/.gitignore
  .build-tools/README.md
  .build-tools/cmd/cmd-bundle-component-metadata.go
  .build-tools/cmd/cmd-gen-component-schema.go
  .build-tools/cmd/root.go
  .build-tools/cmd/utils.go
  .build-tools/component-folders.json
  .build-tools/go.mod
  .build-tools/go.sum
  .build-tools/main.go
  .build-tools/pkg/componentmetadata/find.go
  .build-tools/pkg/componentmetadata/parser.go
  .build-tools/pkg/metadataschema/bundle.go
  .build-tools/pkg/metadataschema/schema.go
  .build-tools/pkg/metadataschema/validators.go
  .github/workflows/components-contrib.yml
  .gitignore
  Makefile
  bindings/azure/servicebusqueues/metadata.yaml
  bindings/http/metadata.yaml
  component-metadata-schema.json
  state/azure/cosmosdb/metadata.yaml
  state/mongodb/metadata.yaml
  tests/e2e/e2e_tests.mk
Labels: automerge
