Repository dapr/components-contrib, pull requests merged in 2022-12, with the labels that each got.

#2335 standardize secretstore metadata parsing
  secretstores/alicloud/parameterstore/parameterstore.go
  secretstores/aws/parameterstore/parameterstore.go
  secretstores/aws/secretmanager/secretmanager.go
  secretstores/azure/keyvault/keyvault.go
  secretstores/gcp/secretmanager/secretmanager.go
  secretstores/hashicorp/vault/vault.go
  secretstores/hashicorp/vault/vault_test.go
  secretstores/huaweicloud/csms/csms.go
  secretstores/kubernetes/kubernetes.go
  secretstores/local/env/envstore.go
  secretstores/local/file/filestore.go
  secretstores/secret_store.go
  secretstores/tencentcloud/ssm/ssm.go
Labels: automerge

#2340 Add AckPolicy option to NATS pub/sub
  pubsub/jetstream/jetstream.go
  pubsub/jetstream/metadata.go
  pubsub/jetstream/metadata_test.go
Labels: documentation required

#2315 Rework JetStream delivery policy
  pubsub/jetstream/jetstream.go
  pubsub/jetstream/metadata.go
  pubsub/jetstream/metadata_test.go
Labels: documentation required

#2352 Check the correct error object in a few places inside blobstorage client
  internal/component/azure/blobstorage/client.go
Labels: automerge

#2344 set default ttl field for cosmosdb to enable ttl support.
  .github/infrastructure/conformance/azure/conf-test-azure-cosmosdb.bicep
Labels: automerge

#2302 Add TTL to postgres state store
  state/azure/cosmosdb/cosmosdb.go
  state/azure/cosmosdb/cosmosdb_test.go
  state/cassandra/cassandra.go
  state/cassandra/cassandra_test.go
  state/memcached/memcached_test.go
  state/oci/objectstorage/objectstorage.go
  state/oci/objectstorage/objectstorage_test.go
  state/oracledatabase/oracledatabase_integration_test.go
  state/oracledatabase/oracledatabaseaccess.go
  state/postgresql/dbaccess.go
  state/postgresql/migrations.go
  state/postgresql/postgresdbaccess.go
  state/postgresql/postgresdbaccess_test.go
  state/postgresql/postgresql.go
  state/postgresql/postgresql_integration_test.go
  state/postgresql/postgresql_test.go
  state/utils/ttl.go
  state/utils/ttl_test.go
  tests/certification/state/postgresql/README.md
  tests/certification/state/postgresql/go.mod
  tests/certification/state/postgresql/postgresql_test.go
  tests/config/state/tests.yml
Labels: automerge

#2228 Add support for Redis 7 in all Dapr Components
  .github/infrastructure/docker-compose-redis7.yml
  .github/workflows/conformance.yml
  bindings/redis/redis.go
  bindings/redis/redis_test.go
  go.mod
  go.sum
  internal/component/redis/redis.go
  internal/component/redis/v8client.go
  internal/component/redis/v9client.go
  lock/redis/standalone.go
  pubsub/redis/redis.go
  pubsub/redis/redis_test.go
  state/redis/redis.go
  state/redis/redis_query.go
  state/redis/redis_test.go
  tests/certification/bindings/redis/go.mod
  tests/certification/bindings/redis/go.sum
  tests/certification/state/redis/go.mod
  tests/certification/state/redis/go.sum
  tests/config/bindings/redis/v6/bindings.yml
  tests/config/bindings/redis/v7/bindings.yml
  tests/config/bindings/tests.yml
  tests/config/pubsub/redis/v6/pubsub.yml
  tests/config/pubsub/redis/v7/pubsub.yml
  tests/config/pubsub/tests.yml
  tests/config/state/redis/v6/statestore.yaml
  tests/config/state/redis/v7/statestore.yaml
  tests/config/state/tests.yml
  tests/conformance/common.go
  tests/conformance/pubsub/pubsub.go
Labels: pinned

#2348 Allow bindings conformance tests for uninitialized components
  tests/conformance/bindings/bindings.go
Labels: automerge

#2276 Add rabbitmq tls metadata
  pubsub/mqtt/metadata.go
  pubsub/mqtt/mqtt.go
  pubsub/mqtt/mqtt_test.go
  pubsub/rabbitmq/metadata.go
  pubsub/rabbitmq/metadata_test.go
  pubsub/rabbitmq/rabbitmq.go
  pubsub/rabbitmq/rabbitmq_test.go
  pubsub/tls.go
  pubsub/tls_test.go
Labels: documentation required

#2281 Add back headers metadata pass in kafka subscribe
  internal/component/kafka/consumer.go
Labels: automerge

#2365 AWS Certification Infrastructure
  .github/infrastructure/terraform/conformance/pubsub/aws/snssqs/snssqs.tf
  .github/workflows/certification.yml
  .github/workflows/conformance.yml
  tests/config/pubsub/aws/snssqs/docker/pubsub.yml
  tests/config/pubsub/aws/snssqs/terraform/pubsub.yml
  tests/config/pubsub/tests.yml
  tests/conformance/README.md
  tests/conformance/common.go
Labels: automerge
