Repository dapr/components-contrib, pull requests merged in 2022-07, with the labels that each got.

#1824 Improvements to S3 binding
  bindings/aws/s3/s3.go
  bindings/aws/s3/s3_test.go
  internal/utils/utils.go
Labels: automerge

#1827 Ensure context propagation in signalr Invoke
  bindings/azure/signalr/signalr.go
  bindings/azure/signalr/signalr_test.go
Labels: automerge

#1828 Improvements to HTTP and graphQL bindings
  bindings/graphql/graphql.go
  bindings/http/http.go
Labels: automerge

#1825 Ensure context propagation in SNS binding
  bindings/aws/sns/sns.go
Labels: automerge

#1835 Updated development docs
  Readme.md
  bindings/Readme.md
  configuration/Readme.md
  docs/developing-component.md
  middleware/Readme.md
  nameresolution/Readme.md
  pubsub/Readme.md
  secretstores/Readme.md
  state/Readme.md
Labels: automerge

#1837 Make metadata keys uniform for Azure Storage components
  authentication/azure/auth.go
  authentication/azure/storage.go
  bindings/azure/blobstorage/blobstorage.go
  bindings/azure/blobstorage/blobstorage_test.go
  bindings/azure/storagequeues/storagequeues.go
  bindings/azure/storagequeues/storagequeues_test.go
  metadata/utils.go
  state/azure/blobstorage/blobstorage.go
  state/azure/tablestorage/tablestorage.go
  state/azure/tablestorage/tablestorage_test.go
  tests/certification/bindings/azure/storagequeues/go.mod
  tests/certification/bindings/azure/storagequeues/go.sum
Labels: automerge, documentation required

#1829 Ensure context propagation in MySQL binding
  bindings/mysql/mysql.go
  bindings/mysql/mysql_test.go
Labels: automerge

#1841 [release-1.8] Azure Blob Storage state store conformance tests
  .github/workflows/conformance.yml
  state/azure/blobstorage/blobstorage.go
  tests/config/bindings/azure/blobstorage/bindings.yml
  tests/config/state/azure/blobstorage/statestore.yaml
  tests/config/state/tests.yml
  tests/conformance/common.go
  tests/conformance/state/state.go
Labels: automerge

#1842 Add support for AAD auth in Azure Storage Queues binding
  authentication/azure/storage.go
  bindings/azure/blobstorage/blobstorage.go
  bindings/azure/eventhubs/eventhubs.go
  bindings/azure/storagequeues/storagequeues.go
  bindings/azure/storagequeues/storagequeues_test.go
  pubsub/azure/eventhubs/eventhubs.go
  state/azure/blobstorage/blobstorage.go
  tests/certification/bindings/azure/blobstorage/go.mod
  tests/certification/bindings/azure/blobstorage/go.sum
  tests/certification/bindings/azure/cosmosdb/go.mod
  tests/certification/bindings/azure/cosmosdb/go.sum
  tests/certification/bindings/azure/eventhubs/go.mod
  tests/certification/bindings/azure/eventhubs/go.sum
  tests/certification/bindings/azure/servicebusqueues/go.mod
  tests/certification/bindings/azure/servicebusqueues/go.sum
  tests/certification/pubsub/azure/eventhubs/go.mod
  tests/certification/pubsub/azure/eventhubs/go.sum
  tests/certification/secretstores/azure/keyvault/go.mod
  tests/certification/secretstores/azure/keyvault/go.sum
  tests/certification/state/azure/tablestorage/go.mod
  tests/certification/state/azure/tablestorage/go.sum
Labels: automerge, documentation required

#1852 Azure AD support in SignalR
  bindings/apns/authorization_builder.go
  bindings/azure/signalr/signalr.go
  bindings/azure/signalr/signalr_test.go
  go.mod
  internal/authentication/azure/auth.go
Labels: automerge

#1820 optimize: add context to huawei/obs
  bindings/huawei/obs/obs.go
  bindings/huawei/obs/obs_service.go
  bindings/huawei/obs/obs_test.go
Labels: automerge

#1877 Removed replace to not use fork
  tests/certification/bindings/alicloud/dubbo/go.mod
  tests/certification/bindings/alicloud/dubbo/go.sum
  tests/certification/bindings/alicloud/nacos/go.mod
  tests/certification/bindings/alicloud/nacos/go.sum
  tests/certification/bindings/azure/blobstorage/go.mod
  tests/certification/bindings/azure/blobstorage/go.sum
  tests/certification/bindings/azure/cosmosdb/go.mod
  tests/certification/bindings/azure/cosmosdb/go.sum
  tests/certification/bindings/azure/eventhubs/go.mod
  tests/certification/bindings/azure/eventhubs/go.sum
  tests/certification/bindings/azure/servicebusqueues/go.mod
  tests/certification/bindings/azure/servicebusqueues/go.sum
  tests/certification/bindings/azure/storagequeues/go.mod
  tests/certification/bindings/azure/storagequeues/go.sum
  tests/certification/bindings/kafka/go.mod
  tests/certification/bindings/kafka/go.sum
  tests/certification/go.mod
  tests/certification/go.sum
  tests/certification/pubsub/azure/eventhubs/go.mod
  tests/certification/pubsub/azure/eventhubs/go.sum
  tests/certification/pubsub/kafka/go.mod
  tests/certification/pubsub/kafka/go.sum
  tests/certification/pubsub/mqtt/go.mod
  tests/certification/pubsub/mqtt/go.sum
  tests/certification/pubsub/rabbitmq/go.mod
  tests/certification/pubsub/rabbitmq/go.sum
  tests/certification/secretstores/azure/keyvault/go.mod
  tests/certification/secretstores/azure/keyvault/go.sum
  tests/certification/state/azure/tablestorage/go.mod
  tests/certification/state/azure/tablestorage/go.sum
  tests/certification/state/postgresql/go.mod
  tests/certification/state/postgresql/go.sum
  tests/certification/state/redis/go.mod
  tests/certification/state/redis/go.sum
  tests/certification/state/sqlserver/go.mod
  tests/certification/state/sqlserver/go.sum
Labels: automerge

#1887 Added pubsub.FeatureSubscribeWildcards capability
  pubsub/feature.go
  pubsub/mqtt/mqtt.go
Labels: automerge

#1857 Calculate Cert test coverage and notify discord monitoring channel
  .github/workflows/certification.yml
Labels: automerge

#1897 modify error msg
  bindings/alicloud/rocketmq/rocketmq.go
Labels: automerge

#1902 Do not skip duplicate actions for conf and cert tests
  .github/workflows/certification.yml
  .github/workflows/conformance.yml
Labels: automerge

#1903 Remove pre-condition from cert & conf test workflow
  .github/workflows/certification.yml
  .github/workflows/conformance.yml
Labels: automerge

#1901 pubsub.mqtt: support multiple wildcards in subscriptions
  pubsub/mqtt/mqtt.go
  pubsub/mqtt/mqtt_test.go
Labels: automerge

#1896 Certification test for Azure Blob storage state store component
  .github/workflows/certification.yml
  tests/certification/state/azure/blobstorage/README.md
  tests/certification/state/azure/blobstorage/blobstorage_test.go
  tests/certification/state/azure/blobstorage/components/aadtest/blobaad.yaml
  tests/certification/state/azure/blobstorage/components/aadtest/localsecrets.yaml
  tests/certification/state/azure/blobstorage/components/basictest/azureblob.yaml
  tests/certification/state/azure/blobstorage/components/basictest/localsecrets.yaml
  tests/certification/state/azure/blobstorage/components/nonexistingcontainertest/azureblob.yaml
  tests/certification/state/azure/blobstorage/components/nonexistingcontainertest/localsecrets.yaml
  tests/certification/state/azure/blobstorage/config.yaml
  tests/certification/state/azure/blobstorage/go.mod
  tests/certification/state/azure/blobstorage/go.sum
Labels: automerge

#1910 Added conformance tests for rabbitmq bindings
  .github/workflows/conformance.yml
  tests/config/bindings/rabbitmq/bindings.yml
  tests/config/bindings/tests.yml
  tests/conformance/common.go
Labels: autoupdate
