Repository dapr/components-contrib, pull requests merged in 2022-10, with the labels that each got.

#2146 deps: updates to latest wapc-go
  go.mod
  go.sum
Labels: automerge

#2143 Convert middlewares from fasthttp to net/http
  internal/httputils/requests.go
  internal/httputils/responses.go
  middleware/http/bearer/bearer_middleware.go
  middleware/http/nethttpadaptor/nethttpadaptor.go
  middleware/http/nethttpadaptor/nethttpadaptor_test.go
  middleware/http/oauth2/oauth2_middleware.go
  middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware.go
  middleware/http/oauth2clientcredentials/oauth2clientcredentials_middleware_test.go
  middleware/http/opa/middleware.go
  middleware/http/opa/middleware_test.go
  middleware/http/ratelimit/ratelimit_middleware.go
  middleware/http/routerchecker/routerchecker_middleware.go
  middleware/http/routerchecker/routerchecker_middleware_test.go
  middleware/http/sentinel/middleware.go
  middleware/http/sentinel/middleware_test.go
  middleware/http/sentinel/rules.go
  middleware/http/wasm/basic/basic.go
  middleware/http/wasm/basic/basic_test.go
  middleware/http/wasm/basic/internal/e2e_test.go
  middleware/middleware.go
Labels: breaking-change, documentation required

#2137 Change coverage threshold to 60 in certification test
  .github/workflows/certification.yml
Labels: automerge

#2180 Add more JetStream options
  pubsub/jetstream/jetstream.go
  pubsub/jetstream/metadata.go
  pubsub/jetstream/metadata_test.go
Labels: automerge

#2192 Merge release 1.9 into master
  .devcontainer/devcontainer.json
  bindings/azure/servicebusqueues/servicebusqueues.go
  internal/component/azure/servicebus/errors.go
  pubsub/azure/servicebus/servicebus.go
Labels: automerge

#2203 Move more code from ASB components into common implementation
  bindings/azure/servicebusqueues/metadata.go
  bindings/azure/servicebusqueues/metadata_test.go
  bindings/azure/servicebusqueues/servicebusqueues.go
  internal/component/azure/servicebus/client.go
  internal/component/azure/servicebus/errors.go
  internal/component/azure/servicebus/message.go
  internal/component/azure/servicebus/message_test.go
  internal/component/azure/servicebus/metadata.go
  internal/component/azure/servicebus/metadata_test.go
  internal/component/azure/servicebus/subscription.go
  internal/component/azure/servicebus/subscription_test.go
  pubsub/azure/servicebus/message.go
  pubsub/azure/servicebus/message_test.go
  pubsub/azure/servicebus/metadata.go
  pubsub/azure/servicebus/servicebus.go
  pubsub/azure/servicebus/servicebus_test.go
Labels: documentation required

#2175 Fix bulk get from gcp secret store
  go.mod
  secretstores/gcp/secretmanager/secretmanager.go
  secretstores/gcp/secretmanager/secretmanager_test.go
Labels: automerge

#2211 New PubSub component: Azure Service Bus Queues
  .build-tools/component-folders.json
  .github/workflows/certification.yml
  .github/workflows/conformance.yml
  bindings/azure/eventhubs/eventhubs_integration_test.go
  bindings/azure/servicebusqueues/servicebusqueues.go
  bindings/rabbitmq/rabbitmq_integration_test.go
  internal/component/azure/servicebus/handler_pubsub.go
  internal/component/azure/servicebus/message_pubsub.go
  internal/component/azure/servicebus/message_pubsub_test.go
  internal/component/azure/servicebus/message_test.go
  internal/component/azure/servicebus/metadata.go
  pubsub/azure/eventhubs/eventhubs_integration_test.go
  pubsub/azure/servicebus/queues/servicebus.go
  pubsub/azure/servicebus/topics/servicebus.go
  test.log
  tests/certification/pubsub/azure/servicebus/servicebus_test.go
  tests/config/pubsub/azure/servicebus/queues/pubsub.yml
  tests/config/pubsub/azure/servicebus/topics/pubsub.yml
  tests/config/pubsub/tests.yml
  tests/conformance/common.go
Labels: automerge, documentation required

#2218 Fix Azure Service Bus cert/conf tests
  .gitignore
  bindings/azure/servicebusqueues/servicebusqueues.go
  test.log
  tests/certification/pubsub/azure/servicebus/topics/README.md
  tests/certification/pubsub/azure/servicebus/topics/components/authentication/localsecrets.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/authentication/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/consumer_one/localsecrets.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/consumer_one/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/consumer_two/localsecrets.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/consumer_two/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/default_ttl/localsecrets.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/default_ttl/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/entity_mgmt/localsecrets.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/entity_mgmt/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/topics/config.yaml
  tests/certification/pubsub/azure/servicebus/topics/go.mod
  tests/certification/pubsub/azure/servicebus/topics/go.sum
  tests/certification/pubsub/azure/servicebus/topics/servicebus_test.go
Labels: automerge

#2219 More fixes to ASB cert tests
  .devcontainer/devcontainer.json
  tests/certification/pubsub/azure/servicebus/topics/components/authentication/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/consumer_one/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/consumer_two/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/default_ttl/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/topics/components/entity_mgmt/service_bus.yaml
  tests/certification/pubsub/azure/servicebus/topics/servicebus_test.go
Labels: automerge

#1941 Initial creation of workflows building block
  .build-tools/component-folders.json
  .build-tools/pkg/metadataschema/schema.go
  .github/infrastructure/conformance/temporal/server/dynamicconfig/README.md
  .github/infrastructure/conformance/temporal/server/dynamicconfig/development-cass.yaml
  .github/infrastructure/conformance/temporal/server/dynamicconfig/development-sql.yaml
  .github/infrastructure/conformance/temporal/server/dynamicconfig/docker.yaml
  .github/infrastructure/conformance/temporal/worker/Dockerfile
  .github/infrastructure/conformance/temporal/worker/go.mod
  .github/infrastructure/conformance/temporal/worker/go.sum
  .github/infrastructure/conformance/temporal/worker/main.go
  .github/infrastructure/docker-compose-temporal.yml
  .github/workflows/conformance.yml
  component-metadata-schema.json
  go.mod
  go.sum
  tests/config/workflows/temporal/workflows.yaml
  tests/config/workflows/tests.yml
  tests/conformance/common.go
  tests/conformance/workflow_test.go
  tests/conformance/workflows/workflows.go
  workflows/README.md
  workflows/metadata.go
  workflows/requests.go
  workflows/responses.go
  workflows/temporal/temporal.go
  workflows/workflow.go
Labels: documentation required

#2240 Add note that pubsub.hazelcast is deprecated
  pubsub/hazelcast/hazelcast.go
Labels: automerge

#2242 Run conf tests for state.mysql against MariaDB too
  .github/infrastructure/docker-compose-mariadb.yml
  .github/infrastructure/docker-compose-mysql.yml
  .github/workflows/conformance.yml
  tests/config/state/mysql/mariadb/statestore.yaml
  tests/config/state/mysql/mysql/statestore.yaml
  tests/config/state/tests.yml
  tests/conformance/common.go
Labels: automerge
