Repository dapr/components-contrib, pull requests merged in 2023-01, with the labels that each got.

#2377 Use message's retain property to cover meta's
  pubsub/mqtt/mqtt.go
  pubsub/mqtt/mqtt_test.go
Labels: automerge, documentation required

#2298 Receiving of custom properties from IoT Hub through endpoint that is compatible with Event Hubs
  pubsub/azure/eventhubs/eventhubs.go
  pubsub/azure/eventhubs/eventhubs_integration_test.go
  tests/certification/pubsub/azure/eventhubs/send-iot-device-events.sh
  tests/scripts/send-iot-device-events.sh
Labels: automerge, documentation required

#2416 AWS SNS/SQS PubSub Certification Tests - Exiting Queue/Topics tests
  .github/infrastructure/terraform/certification/pubsub/aws/snssqs/snssqs.tf
  .github/workflows/certification.yml
  tests/certification/pubsub/aws/snssqs/README.md
  tests/certification/pubsub/aws/snssqs/components/existing_queue/localsecrets.yaml
  tests/certification/pubsub/aws/snssqs/components/existing_queue/pubsub.yaml
  tests/certification/pubsub/aws/snssqs/snssqs_test.go
Labels: automerge

#2418 Fix State Azure Blob cert test
  tests/certification/state/azure/blobstorage/components/aadtest/blobaad.yaml
Labels: automerge

#2426 [AWS DynamoDB] Fixes Incorrect Implementation of the Partition Key Metadata Field
  state/aws/dynamodb/dynamodb.go
  state/aws/dynamodb/dynamodb_test.go
Labels: documentation required

#2430 Fix heartbeat typo
  pubsub/jetstream/jetstream.go
  pubsub/jetstream/metadata.go
  pubsub/jetstream/metadata_test.go
  tests/config/pubsub/jetstream/pubsub.yml
Labels: automerge

#2415 Adding redisDB metadata
  configuration/redis/internal/redis_value.go
  configuration/redis/internal/redis_value_test.go
  configuration/redis/metadata.go
  configuration/redis/redis.go
  configuration/redis/redis_test.go
Labels: automerge

#2447 Use sync.Map for ASB active messages
  internal/component/azure/servicebus/subscription.go
Labels: automerge

#2449 bindings.localstorage fixes
  bindings/localstorage/localstorage.go
  bindings/localstorage/localstorage_test.go
  tests/certification/bindings/localstorage/components/localstorage.yaml
  tests/certification/bindings/localstorage/localstorage_test.go
Labels: automerge

#2446 Fix mqtt pubsub: remove republishing when application is unhealthy
  .github/workflows/conformance.yml
  pubsub/mqtt3/metadata.go
  pubsub/mqtt3/mqtt.go
  tests/certification/pubsub/mqtt3/components/consumer2/mqtt.yaml
  tests/certification/pubsub/mqtt3/go.mod
  tests/certification/pubsub/mqtt3/go.sum
  tests/config/pubsub/mqtt3/mosquitto/pubsub.yml
  tests/config/pubsub/tests.yml
Labels: automerge, documentation required

#2423 Apache Pulsar Certification Tests
  .github/workflows/certification.yml
  tests/certification/flow/watcher/watcher.go
  tests/certification/pubsub/pulsar/README.md
  tests/certification/pubsub/pulsar/components/consumer_one/pulsar.yml
  tests/certification/pubsub/pulsar/components/consumer_three/pulsar.yml
  tests/certification/pubsub/pulsar/components/consumer_two/pulsar.yml
  tests/certification/pubsub/pulsar/config.yaml
  tests/certification/pubsub/pulsar/docker-compose.yml
  tests/certification/pubsub/pulsar/go.mod
  tests/certification/pubsub/pulsar/go.sum
  tests/certification/pubsub/pulsar/pulsar_test.go
Labels: automerge

#2456 Replace deprecated zookeeper library
  go.mod
  go.sum
  state/zookeeper/zk.go
  state/zookeeper/zk_mock.go
  state/zookeeper/zk_test.go
Labels: automerge

#2457 Update Aerospike statestore dependencies
  go.mod
  go.sum
  state/aerospike/aerospike.go
Labels: automerge

#2462 Support PEM certificates from Azure AD
  internal/authentication/azure/auth.go
Labels: automerge

#2452 Add tracing headers to HTTP request
  bindings/http/http.go
  bindings/http/http_test.go
Labels: automerge

#2470 Add security token header support
  bindings/http/http.go
  bindings/http/http_test.go
  bindings/http/metadata.yaml
Labels: automerge

#2475 Add schema support to apache pulsar
  go.mod
  go.sum
  pubsub/pulsar/metadata.go
  pubsub/pulsar/pulsar.go
  pubsub/pulsar/pulsar_test.go
  tests/certification/flow/watcher/watcher.go
  tests/certification/pubsub/pulsar/components/consumer_four/pulsar.yaml
  tests/certification/pubsub/pulsar/go.mod
  tests/certification/pubsub/pulsar/go.sum
  tests/certification/pubsub/pulsar/pulsar_test.go
Labels: automerge

#2477 mdns: shut down on context cancelation and not on signal
  nameresolution/mdns/mdns.go
Labels: automerge

#2479 Firestore State Store: Adds `noindex` option to skip indexing of value.
  state/gcp/firestore/firestore.go
  state/gcp/firestore/firestore_test.go
Labels: automerge
