Repository dapr/components-contrib, pull requests merged in 2025-08, with the labels that each got.

#3853 feat: Add support for replicateSubscriptionState in Pulsar pubsub component
  pubsub/pulsar/metadata.go
  pubsub/pulsar/metadata.yaml
  pubsub/pulsar/pulsar.go
  pubsub/pulsar/pulsar_test.go
Labels: documentation required, autoupdate

#3806 Supporting more properties for rabbitmq
  bindings/rabbitmq/rabbitmq.go
  bindings/rabbitmq/rabbitmq_integration_test.go
  common/component/rabbitmq/rabbitmq.go
  common/component/rabbitmq/rabbitmq_test.go
  conversation/deepseek/metadata.yaml
  metadata/utils.go
  metadata/utils_test.go
  pubsub/rabbitmq/metadata.go
  pubsub/rabbitmq/metadata.yaml
  pubsub/rabbitmq/metadata_test.go
  pubsub/rabbitmq/rabbitmq.go
  pubsub/rabbitmq/rabbitmq_test.go
  tests/certification/bindings/rabbitmq/components/metadata/rabbitmq.yaml
  tests/certification/bindings/rabbitmq/rabbitmq_test.go
  tests/certification/pubsub/rabbitmq/components/metadata/rabbitmq-metadata.yaml
  tests/certification/pubsub/rabbitmq/rabbitmq_test.go
Labels: autoupdate

#3797 Add Azure spiffe oidc auth profile
  common/authentication/aws/x509.go
  common/authentication/aws/x509_test.go
  common/authentication/azure/auth.go
  common/authentication/azure/spiffe.go
  common/component/azure/blobstorage/client.go
  state/azure/blobstorage/v2/metadata.yaml
Labels: autoupdate

#3708 Add support for multiple keys per secret
  common/authentication/aws/client_fake.go
  secretstores/aws/secretmanager/metadata.yaml
  secretstores/aws/secretmanager/secretmanager.go
  secretstores/aws/secretmanager/secretmanager_test.go
Labels: documentation required

#3712 Add option to ser/deser avro to/from AvroJSON if the component is configured to do so.
  bindings/kafka/metadata.yaml
  common/component/kafka/kafka.go
  common/component/kafka/kafka_test.go
  common/component/kafka/metadata.go
  common/component/kafka/mocks/mock_ISchemaRegistryClient.go
  docs/developing-component.md
  go.mod
  go.sum
  pubsub/kafka/metadata.yaml
  tests/certification/go.mod
  tests/certification/go.sum
Labels: autoupdate
